server:
  port: 8081

spring:
  application:
    name: PRODUCT-SERVER
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

